# Generated by Django 3.1.7 on 2021-05-18 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_check'),
    ]

    operations = [
        migrations.DeleteModel(
            name='check',
        ),
    ]
